version: '3.7'

services:
  nimful-frontend:
    image: nimful-frontend
    container_name: nimful-frontend
    ports:
      - 3000
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nimful-nginx
    ports:
      - 80:80
    depends_on:
      - nimful-frontend